package bot.exchange.statemachine;

public enum Event {
    MAIN_MENU, MY_RATES, FROM_CURRENCY, TO_CURRENCY, CURRENCY_AMOUNT, PRE_CONFIRM_EXCHANGE, CONFIRM_EXCHANGE, BANK_RATES, CREATE_DEPOSIT, DEPOSIT_RULES
}
